### ISSUE TITLE
Request/Suggestion - allow sharing bootloader folder with hekate

### ISSUE THREAD

**Issue by pixeltester** [Storm21CH/argon-nx#1]
Would you consider sharing the ArgonNX-SE bootloader folder with hekate? It would be a really nice enhancement to switch to it or make it optional for hekate users for a cleaner sd card with no duplicate files:

The directories would be as follows:

argon/logos/ becomes bootloader/res/
argon/sys/ becomes bootloader/sys/ (minerva and lp0 can be shared)
argon/payloads/ becomes bootloader/payloads/ (payloads shared)
argon/screenshots/ becomes bootloader/screenshots/

**Comment by Storm21CH** [comment]
Sorry, i don't like it, if hekate updates, all must be changed... But thank you for suggestion
