### ISSUE TITLE
Question about files included on the Released zip file

### ISSUE THREAD

**Issue by impeeza** [Storm21CH/argon-nx#10]
Hello there,

Thanks a lot for all your hard work.

I wonder what is the sysmodule included on the zip file:

ArgonNX-SE 1.9 SD Files and Payload\atmosphere\contents\010000000000100B\exefs.nsp

what that nsp does?

thanks a lot.

**Comment by Storm21CH** [comment]
Hello impeeza 

Mariko and AULA "Reboot to Payload" function chain...
Per system modules to nro (010000000000100B Nintendo Store Button)

This loads the nro in switch folder...

**Comment by impeeza** [comment]
Thanks for answering.  regards.
