### ISSUE TITLE
Request : Icon for Lakka and Common Problem resolver

### ISSUE THREAD

**Issue by juju35** [Storm21CH/argon-nx#4]
Hello,

Do you have an icon for Lakka and also for Common Problem Resolver ?

Thanks a lot

**Comment by juju35** [comment]
[Argon-Boot icon.zip](https://github.com/Storm21CH/argon-nx/files/7896425/Argon-Boot.icon.zip)
Here is photoshop file to generate new icons

**Comment by Storm21CH** [comment]
Hi
You have already created the icons in the file. They just have to be saved correctly and they're done.

**Comment by juju35** [comment]
I know that. I uploaded to share. It could be included in project resources

**Comment by Storm21CH** [comment]
I can integrate the icons into the release. But the original icon template is from mrdude and I can't offer that here. Thank you!
