### ISSUE TITLE
how can I change the English of the start menu？

### ISSUE THREAD

**Issue by sskyNS** [Storm21CH/argon-nx#7]
Please how can I change the English of the start menu, people in my country want to use their language, so that it will look more familiar, thank you for your efforts, look forward to reply!

**Comment by Storm21CH** [comment]
Hello
You mean add another language? Currently the languages are hardcoded in the source. No other languages can be added. Maybe I'll change that when I get a chance...

**Comment by sskyNS** [comment]
Thank you for your reply.Yes, I did a simple Chinese translation of him a while ago. The argon gui. bin file is a text that can be translated, but after using the translation software Passolo for translation, the image appeared garbled, both in German and English.Therefore, I would like to request your help. This may require some programming knowledge to solve, and I am powerless to do so. I hope you can help me complete it.

**Comment by sskyNS** [comment]
/

**Comment by Storm21CH** [comment]
Problem is no Unicode Font... Special Characters. That have fist added.

Cant see the Image...

**Comment by sskyNS** [comment]
Yes,  Do you involved in the development of the previous version of Argon for that project？The underlying code should be available from them if needed.
![IMG_4538](https://github.com/Storm21CH/ArgonNX-SE/assets/121209531/8457f388-d88f-4089-b59c-043698d7a284)

**Comment by Storm21CH** [comment]
I've played around with all versions. Do you mean the first LVGL version or even older?
For Chinese writing, the font must first be integrated into LVGL. Then a translation can also take place. But this has to be built into the source, otherwise it won't work. Did you just do this with the hex editor? That definitely doesn't work.

**Comment by sskyNS** [comment]
So I need your help, I am unprepared for the code. I can only provide translated text and sufficient testing time.

**Comment by Storm21CH** [comment]
You have a Chinese TTF font file? Needed for Font building... Translated Text later. But I can't promise!

**Comment by sskyNS** [comment]
I'll translate it and send it to you, do you have the contact details of Discord or gbatemp?

**Comment by sskyNS** [comment]
I did not find the file for the TFF language text, where can it be found, find him I can start translating.

**Comment by sskyNS** [comment]
By the way, would you be interested in participating in the development of a program? Regarding game grouping, if you are interested, we can further communicate.

**Comment by Storm21CH** [comment]
I need a TTF font that I can use! I don't speak Chinese and don't know the characters. So I need this from someone first. 

Yes on gbatemp without CH... 

Sorry I only have time for my projects.

**Comment by sskyNS** [comment]
[short-baby-font.zip](https://github.com/Storm21CH/ArgonNX-SE/files/12706342/short-baby-font.zip)

**Comment by sskyNS** [comment]
You can check to see if this is feasible. If so, I will cooperate with you to complete the translation work.

**Comment by Storm21CH** [comment]
This is not Chinese TTF Font...

**Comment by sskyNS** [comment]
[AaJiJiaHei.zip](https://github.com/Storm21CH/ArgonNX-SE/files/12707902/AaJiJiaHei.zip)

**Comment by sskyNS** [comment]
[ttf simple Chinese.zip](https://github.com/Storm21CH/ArgonNX-SE/files/12707908/ttf.simple.Chinese.zip)
This is a ttf font for Simplified Chinese, I extracted it from my computer

**Comment by sskyNS** [comment]
This is definitely available,

**Comment by sskyNS** [comment]
How is it going

**Comment by MicrosoftWindows10** [comment]
我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。
另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。

**Comment by MicrosoftWindows10** [comment]
> This is not Chinese TTF Font...

Dude, he is actually a plagiarist, please don't help him.
He will sell the project to others for a fee.

**Comment by sskyNS** [comment]
Aha? How do you distort the facts? How can I sell GitHub projects? What are you talking about? People who slander others in China @MicrosoftWindows10

**Comment by sskyNS** [comment]
> 我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。 另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。
I can imagine how you tried your best to insult us in other parts, so I just want to say one thing. When you slander others with countless developers, you actually show the ugliest and most real appearance in your heart.

**Comment by MicrosoftWindows10** [comment]
> Aha? How do you distort the facts? How can I sell GitHub projects? What are you talking about? People who slander others in China @MicrosoftWindows10

Hey, man, listen to me, it's true.
He is a thief who steals the atmosphere of switch.
He aggregates these free projects and sells them to others for a fee.
For example, in this video, he closed the comment area and only fans can unlock it.
![IMG_20231004_095838](https://github.com/Storm21CH/ArgonNX-SE/assets/43537661/dc4da57f-33e8-45e8-9960-886c1d382104)
![S31004-09554738_tv danmaku bili](https://github.com/Storm21CH/ArgonNX-SE/assets/43537661/37266ab3-2cce-4aff-9ce5-e06d5bdd2a92)

**Comment by MicrosoftWindows10** [comment]
> > 我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。 另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。
> > I can imagine how you tried your best to insult us in other parts, so I just want to say one thing. When you slander others with countless developers, you actually show the ugliest and most real appearance in your heart.

还搁这给我装呢？奸商小丑一个。国内小白圈内丢丢人也就算了，别丢到国外去。怎么心虚关issue啊？🤣👉💩
https://space.bilibili.com/679023184?share_medium=android&=copy_link&bbid=XY61C0F607264FC6318A92B9E13C65DB7CD3C&ts=1696385090750，

**Comment by sskyNS** [comment]
> > Aha? How do you distort the facts? How can I sell GitHub projects? What are you talking about? People who slander others in China @MicrosoftWindows10
> 
> Hey, man, listen to me, it's true. He is a thief who steals the atmosphere of switch. He aggregates these free projects and sells them to others for a fee. For example, in this video, he closed the comment area and only fans can unlock it. ![IMG_20231004_095838](https://user-images.githubusercontent.com/43537661/272441684-dc4da57f-33e8-45e8-9960-886c1d382104.jpg) ![S31004-09554738_tv danmaku bili](https://user-images.githubusercontent.com/43537661/272441711-37266ab3-2cce-4aff-9ce5-e06d5bdd2a92.png)

If you want to know the reason, I can tell you separately. Don't carry out your so-called attacks here. These are meaningless. As a video worker, I think it is necessary for you to understand what you call "trafficking"? If you are just an ordinary person, what does what do you mean to me? Have you achieved what you call these goals?

**Comment by MicrosoftWindows10** [comment]
> > 我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。 另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。
> > I can imagine how you tried your best to insult us in other parts, so I just want to say one thing. When you slander others with countless developers, you actually show the ugliest and most real appearance in your heart.

还搁这给我装呢？奸商小丑一个。国内小白圈内丢丢人也就算了，别丢到国外去。怎么心虚关issue啊？🤣👉💩https://space.bilibili.com/679023184，感情这不是你，是出生。

**Comment by sskyNS** [comment]
> > > 我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。 另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。
> > > I can imagine how you tried your best to insult us in other parts, so I just want to say one thing. When you slander others with countless developers, you actually show the ugliest and most real appearance in your heart.
> 
> 还搁这给我装呢？奸商小丑一个。国内小白圈内丢丢人也就算了，别丢到国外去。怎么心虚关issue啊？🤣👉💩[https://space.bilibili.com/679023184，感情这不是你，是出生。](https://space.bilibili.com/679023184%EF%BC%8C%E6%84%9F%E6%83%85%E8%BF%99%E4%B8%8D%E6%98%AF%E4%BD%A0%EF%BC%8C%E6%98%AF%E5%87%BA%E7%94%9F%E3%80%82)

Are you really in a hurry? It has nothing to do with me to affect your interests. I only care about the problem itself.I repeat again that this is not the place where you perform crosstalk, issue = problem solving.It's not your part of performing crosstalk and splashing 😄

**Comment by MicrosoftWindows10** [comment]
> > > > 我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。 另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。
> > > > I can imagine how you tried your best to insult us in other parts, so I just want to say one thing. When you slander others with countless developers, you actually show the ugliest and most real appearance in your heart.
> > 
> > 
> > 还搁这给我装呢？奸商小丑一个。国内小白圈内丢丢人也就算了，别丢到国外去。怎么心虚关issue啊？🤣👉💩[https://space.bilibili.com/679023184，感情这不是你，是出生。](https://space.bilibili.com/679023184%EF%BC%8C%E6%84%9F%E6%83%85%E8%BF%99%E4%B8%8D%E6%98%AF%E4%BD%A0%EF%BC%8C%E6%98%AF%E5%87%BA%E7%94%9F%E3%80%82)
> 
> Are you really in a hurry? It has nothing to do with me to affect your interests. I only care about the problem itself.I repeat again that this is not the place where you perform crosstalk, issue = problem solving.It's not your part of performing crosstalk and splashing 😄

别搁这用你那破烂机翻了，看的人头疼，小丑就是小丑🤣👉🤡，加戏可以，别把自己骗了就行了。真以为自己是大佬？也就骗骗b站的小白。

**Comment by sskyNS** [comment]
> > > > > 我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。 另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。
> > > > > I can imagine how you tried your best to insult us in other parts, so I just want to say one thing. When you slander others with countless developers, you actually show the ugliest and most real appearance in your heart.
> > > 
> > > 
> > > 还搁这给我装呢？奸商小丑一个。国内小白圈内丢丢人也就算了，别丢到国外去。怎么心虚关issue啊？🤣👉💩[https://space.bilibili.com/679023184，感情这不是你，是出生。](https://space.bilibili.com/679023184%EF%BC%8C%E6%84%9F%E6%83%85%E8%BF%99%E4%B8%8D%E6%98%AF%E4%BD%A0%EF%BC%8C%E6%98%AF%E5%87%BA%E7%94%9F%E3%80%82)
> > 
> > 
> > Are you really in a hurry? It has nothing to do with me to affect your interests. I only care about the problem itself.I repeat again that this is not the place where you perform crosstalk, issue = problem solving.It's not your part of performing crosstalk and splashing 😄
> 
> 别搁这用你那破烂机翻了，看的人头疼，小丑就是小丑🤣👉🤡，加戏可以，别把自己骗了就行了。真以为自己是大佬？也就骗骗b站的小白。
OK, you go on. The tutorial is said to deceive people, so why do you use these means to attack others here? Do you want to  to gain a sense of existence?🤔 I don't need to explain more to you. While you and other developers are communicating, they are also asking me about the reason. 😆

**Comment by MicrosoftWindows10** [comment]
> > > > > > 我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。 另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。
> > > > > > I can imagine how you tried your best to insult us in other parts, so I just want to say one thing. When you slander others with countless developers, you actually show the ugliest and most real appearance in your heart.
> > > > 
> > > > 
> > > > 还搁这给我装呢？奸商小丑一个。国内小白圈内丢丢人也就算了，别丢到国外去。怎么心虚关issue啊？🤣👉💩[https://space.bilibili.com/679023184，感情这不是你，是出生。](https://space.bilibili.com/679023184%EF%BC%8C%E6%84%9F%E6%83%85%E8%BF%99%E4%B8%8D%E6%98%AF%E4%BD%A0%EF%BC%8C%E6%98%AF%E5%87%BA%E7%94%9F%E3%80%82)
> > > 
> > > 
> > > Are you really in a hurry? It has nothing to do with me to affect your interests. I only care about the problem itself.I repeat again that this is not the place where you perform crosstalk, issue = problem solving.It's not your part of performing crosstalk and splashing 😄
> > 
> > 
> > 别搁这用你那破烂机翻了，看的人头疼，小丑就是小丑🤣👉🤡，加戏可以，别把自己骗了就行了。真以为自己是大佬？也就骗骗b站的小白。
> > OK, you go on. The tutorial is said to deceive people, so why do you use these means to attack others here? Do you want to  to gain a sense of existence?🤔 I don't need to explain more to you. While you and other developers are communicating, they are also asking me about the reason. 😆

毕竟你是4000+的货色啊，怎么比得过你呢🤣👉💩

**Comment by sskyNS** [comment]
> > > > > > > 我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。 另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。
> > > > > > > I can imagine how you tried your best to insult us in other parts, so I just want to say one thing. When you slander others with countless developers, you actually show the ugliest and most real appearance in your heart.
> > > > > 
> > > > > 
> > > > > 还搁这给我装呢？奸商小丑一个。国内小白圈内丢丢人也就算了，别丢到国外去。怎么心虚关issue啊？🤣👉💩[https://space.bilibili.com/679023184，感情这不是你，是出生。](https://space.bilibili.com/679023184%EF%BC%8C%E6%84%9F%E6%83%85%E8%BF%99%E4%B8%8D%E6%98%AF%E4%BD%A0%EF%BC%8C%E6%98%AF%E5%87%BA%E7%94%9F%E3%80%82)
> > > > 
> > > > 
> > > > Are you really in a hurry? It has nothing to do with me to affect your interests. I only care about the problem itself.I repeat again that this is not the place where you perform crosstalk, issue = problem solving.It's not your part of performing crosstalk and splashing 😄
> > > 
> > > 
> > > 别搁这用你那破烂机翻了，看的人头疼，小丑就是小丑🤣👉🤡，加戏可以，别把自己骗了就行了。真以为自己是大佬？也就骗骗b站的小白。
> > > OK, you go on. The tutorial is said to deceive people, so why do you use these means to attack others here? Do you want to  to gain a sense of existence?🤔 I don't need to explain more to you. While you and other developers are communicating, they are also asking me about the reason. 😆
> 
> 毕竟你是4000+的货色啊，怎么比得过你呢🤣👉💩
Your verbal attack can only mean that you may lack some kind of innate family upbringing, and he can't prove anything. The more anxious people are, the more they say that there is no bottom line and principle.

**Comment by MicrosoftWindows10** [comment]
> > > > > > > > 我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。 另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。
> > > > > > > > I can imagine how you tried your best to insult us in other parts, so I just want to say one thing. When you slander others with countless developers, you actually show the ugliest and most real appearance in your heart.
> > > > > > 
> > > > > > 
> > > > > > 还搁这给我装呢？奸商小丑一个。国内小白圈内丢丢人也就算了，别丢到国外去。怎么心虚关issue啊？🤣👉💩[https://space.bilibili.com/679023184，感情这不是你，是出生。](https://space.bilibili.com/679023184%EF%BC%8C%E6%84%9F%E6%83%85%E8%BF%99%E4%B8%8D%E6%98%AF%E4%BD%A0%EF%BC%8C%E6%98%AF%E5%87%BA%E7%94%9F%E3%80%82)
> > > > > 
> > > > > 
> > > > > Are you really in a hurry? It has nothing to do with me to affect your interests. I only care about the problem itself.I repeat again that this is not the place where you perform crosstalk, issue = problem solving.It's not your part of performing crosstalk and splashing 😄
> > > > 
> > > > 
> > > > 别搁这用你那破烂机翻了，看的人头疼，小丑就是小丑🤣👉🤡，加戏可以，别把自己骗了就行了。真以为自己是大佬？也就骗骗b站的小白。
> > > > OK, you go on. The tutorial is said to deceive people, so why do you use these means to attack others here? Do you want to  to gain a sense of existence?🤔 I don't need to explain more to you. While you and other developers are communicating, they are also asking me about the reason. 😆
> > 
> > 
> > 毕竟你是4000+的货色啊，怎么比得过你呢🤣👉💩
> > Your verbal attack can only mean that you may lack some kind of innate family upbringing, and he can't prove anything. The more anxious people are, the more they say that there is no bottom line and principle.

你不是装外国人装的挺像吗？怎么你们外国人也说4000+，你还知道什么意思？🤣👉💩

**Comment by sskyNS** [comment]
> > > > > > > > > 我超，这位不是那谁奸商吗，又搁这缝合大气层整合包呢？🤣👉🤡。 另外，一个引导界面中文文本，给人家开发者发个全文本的ttf也是个人才。
> > > > > > > > > I can imagine how you tried your best to insult us in other parts, so I just want to say one thing. When you slander others with countless developers, you actually show the ugliest and most real appearance in your heart.
> > > > > > > 
> > > > > > > 
> > > > > > > 还搁这给我装呢？奸商小丑一个。国内小白圈内丢丢人也就算了，别丢到国外去。怎么心虚关issue啊？🤣👉💩[https://space.bilibili.com/679023184，感情这不是你，是出生。](https://space.bilibili.com/679023184%EF%BC%8C%E6%84%9F%E6%83%85%E8%BF%99%E4%B8%8D%E6%98%AF%E4%BD%A0%EF%BC%8C%E6%98%AF%E5%87%BA%E7%94%9F%E3%80%82)
> > > > > > 
> > > > > > 
> > > > > > Are you really in a hurry? It has nothing to do with me to affect your interests. I only care about the problem itself.I repeat again that this is not the place where you perform crosstalk, issue = problem solving.It's not your part of performing crosstalk and splashing 😄
> > > > > 
> > > > > 
> > > > > 别搁这用你那破烂机翻了，看的人头疼，小丑就是小丑🤣👉🤡，加戏可以，别把自己骗了就行了。真以为自己是大佬？也就骗骗b站的小白。
> > > > > OK, you go on. The tutorial is said to deceive people, so why do you use these means to attack others here? Do you want to  to gain a sense of existence?🤔 I don't need to explain more to you. While you and other developers are communicating, they are also asking me about the reason. 😆
> > > 
> > > 
> > > 毕竟你是4000+的货色啊，怎么比得过你呢🤣👉💩
> > > Your verbal attack can only mean that you may lack some kind of innate family upbringing, and he can't prove anything. The more anxious people are, the more they say that there is no bottom line and principle.
> 
> 你不是装外国人装的挺像吗？怎么你们外国人也说4000+，你还知道什么意思？🤣👉💩

Well, you seem to have lost your mind. When you can say words that hurt others, I think you have lost. But I'm happy to continue to chat with you for a while.
