### ISSUE TITLE
New language text added

### ISSUE THREAD

**Issue by sskyNS** [Storm21CH/argon-nx#8]

**Comment by Storm21CH** [comment]
Got it... Thanks

**Comment by sskyNS** [comment]
https://github.com/sskyNS/ArgonNX-SE/blob/master/ArgonText-1.0.json

**Comment by sskyNS** [comment]
https://github.com/sskyNS/ArgonNX-SE/blob/master/Commonly%20used%20Chinese%20Unicode%20(3500%20words):

**Comment by sskyNS** [comment]
https://github.com/sskyNS/ArgonNX-SE/blob/master/Argon%20text-2.0.json

**Comment by sskyNS** [comment]
//neu alle Texte 2
    lbl_title_startCFW = SYMBOL_REBOOT" 启动虚拟系统";//Titel Label Start CFW
    lbl_title_chooseEmunand = SYMBOL_WARNING" 选择 Emunand";//Titel Label wähle Emunand
    lbl_title_chooseEmuMMC = SYMBOL_WARNING" 选择 EmuMMC";//Titel Label wähle EmuMMC
    lbl_PartSDswitch_SD = "虚拟系统文件";//Button Label Partition / SD Emunand SD Files
    lbl_PartSDswitch_Part = "虚拟系统分区";//Button Label Partition / SD Emunand Partition

**Comment by sskyNS** [comment]
"Chinese"=简体中文
"RTC /n time and date"=当前时间\n和日期

**Comment by Storm21CH** [comment]
Here you have a test version for your private use. Looks very good in my opinion! Please check your texts as far as possible and whether there are any missing characters.
Install argon 1.9 and replace argon-nx-gui.bin. Have fun!

Some of the buttons are mapped to a fixed size so that everything fits. Like Reset, OK, Cancel, Reload etc. and the file manager buttons. They stay in English. I tried that back then with German, but there were a lot of UI problems because the texts weren't the same length.

[argon-nx-gui.zip](https://github.com/Storm21CH/ArgonNX-SE/files/13380245/argon-nx-gui.zip)

**Comment by sskyNS** [comment]
Well, the current beta version is actually not much of a problem, some problems are basically ignored, if those secondary menus can't be translated, the basic version can be completed, just add the language icon.
lbl_rtc_time = "当前时间\n和日期";//Button Label RTC Zeit und Datum bearbeiten


更改内容：
    //neu alle Texte
    lbl_title_power = SYMBOL_POWER" 电源选项";//Titel Label Power Tools
    lbl_title_system = SYMBOL_SETTINGS" 系统选项";//Titel Label System Tools
    lbl_reboot_rcm = "重启至 RCM模式";//Button Label Reboot RCM
    lbl_reboot_ofw = "重启至 正版系统";//Button Label Reboot OFW
    lbl_reload_menu = "重启至 主界面";//Button Label Reload Menu
    lbl_power_off = "关闭电源";//Button Label Power Off
    lbl_filemanager = "文件管理器";//Button Label Filemanager
    lbl_win_filemanager = "文件管理器";//Header Label Win Filemanager
    lbl_ums_sd = "通过挂载 SD卡\n#FF8000 读取/写入.#";//Button Label UMS SD Card
    lbl_autolaunch_pl = "自动启动\nPayload";//Button Label Autolaunch Payload
    lbl_info = "参数信息";//Button Label Info
    lbl_lang = "语言\n设定";//Button Label Sprache einstellen
    
    //neu alle Texte
    mbox_lang_title = "#FF8000 请选择界面语言...#";//Funktion Sprache einstellen, Titel mbox Sprache

//Funktionen Texte
	mbox_scrsh_sav = SYMBOL_CAMERA"  #FFDD00 保存截图！...#";//Funktion Screenshot speichern
	mbox_scrsh_sav_ok = SYMBOL_CAMERA"  #96FF00 截图已保存!#";//Funktion Screenshot gespeichert
	mbox_scrsh_fail = SYMBOL_WARNING"  #FFDD00 截图失败!#";//Funktion Screenshot Fehler
	mbox_reload = "#FF8000 是否确定需要#\n#FF8000 重新启动应用程序?#";//Funktion Reload mbox Text

**Comment by sskyNS** [comment]
[zh-cn.zip](https://github.com/Storm21CH/ArgonNX-SE/files/14969252/zh-cn.zip)
[screenshots.zip](https://github.com/Storm21CH/ArgonNX-SE/files/14969265/screenshots.zip)
