### ISSUE TITLE
When I load up Argon this happens

### ISSUE THREAD

**Issue by voidxO7** [Storm21CH/argon-nx#9]
https://github.com/Storm21CH/ArgonNX-SE/assets/140977903/9f007a22-69ac-4eef-85b6-8670179bfa53

**Comment by voidxO7** [comment]
The button I clicked was the vol+ button.

**Comment by Storm21CH** [comment]
Volume+ do nothing. More the Power button.
Never see that... SD Files sure not on its place or have no archiv bit...
